package pl.school.model.enums;

public enum SubjectEnum {
    MOLECULAR_BIOLOGY,
    GENERAL_BIOLOGY,
    GENERAL_CHEMISTRY,
    ORGANIC_CHEMISTRY,
    MACROECONOMICS,
    MICROECONOMICS,
    BASIC_OF_MARKETING,
    ACCOUNTANCY,
    LABOR_LAW,
    PRACTICAL_LOGIC,
    DESCRIPTIVE_GEOMETRY,
    TECHNICAL_DRAWING,
    DATABASES,
    COMPUTER_NETWORKS,
    TRANSPORT_LAW,
    CARGO_TRANSPORTATION
}
